config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Articles Routes
  get '/articles', to: 'articles#index' ,as: :articles # articles_path => '/articles'

  get '/articles/new', to: 'articles#new', as: :new_article # new_article_path => '/articles/new'
  post '/articles', to: 'articles#create'

  get '/articles/:id/edit', to: 'articles#edit', as: :edit_article # edit_article_path(:id) => '/articles/:id/edit'
  patch '/articles/:id', to: 'articles#update'

  delete '/articles/:id', to: 'articles#destroy', as: :delete_article
  
  get '/articles/:id', to: 'articles#show' , as: :article # article_path(:id) => '/articles/:id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(updated_at: :desc) #method chaining
  end

  def show
    @article = Article.find(params[:id]) 
  end

  def new
    @article = Article.new
  end

  def create
    #binding.break
    # @article = Article.new
    # @article.title = params[:title]
    # @article.body = params[:body]
    # @article.author_name = params[:author_name]
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit 
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: "Successfully Updated."
    else
      render :edit, status: :unprocessable_entity #error 422
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path ##, notice: 'Article was successfully deleted.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :author_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :author_name %>
    <%= form.text_field :author_name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>


<div>
  <%= link_to "Back To Articles", articles_path %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Body</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %> </td>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <td><%= article.author_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Create New Article", new_article_path %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<p
  style="padding: 2px 1px; background-color: green; color: white; border-radius: 5px; margin-right: auto;"
><%= notice %></p>

<%= link_to "Back to Articles", articles_path%>
<h1><%= @article.title%></h1>
<p><%= @article.body%></p>
<p>Created at: <%= @article.created_at%></p>
<p>Updated at: <%= @article.updated_at%></p>
<p>Author: <%= @article.author_name%></p>

<div>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_to "Destroy", delete_article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Confirm deletion?"
  } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# <h1>Nav</h1> %>
    <div>
      <%= yield %>
    </div>
    <%# <h1>Footer</h1> %>
  </body>
</html>